import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { ThemeProvider } from "@/components/theme-provider";
=======
>>>>>>> 755438e1a05707fe5f12fd696fac449d95e9349a

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
        {children}
      </ThemeProvider>
        </body>
=======
      <body className={inter.className}>{children}</body>
>>>>>>> 755438e1a05707fe5f12fd696fac449d95e9349a
    </html>
  );
}
